config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index", via: :get

  resources :customers do
    member do
      get :delete
    end
  end

  resources :cars do
    member do
      get :delete
    end
  end

  namespace :authentication, path: "", as: "" do
    resources :users, only: [:new, :create], path: "/register", path_names: { new: "" }
    resources :sessions, only: [:new, :create, :destroy], path: "/login", path_names: { new: "" }
  end

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  match "*path", to: "application#handle_404", via: :all
end

app/helpers/shared/delete_helper.rb
module Shared
  module DeleteHelper
    def association_warning_msg(name, objects_name)
      "Deleting #{name} will remove the association with all associated #{objects_name}.

        Are you sure you want to continue?"
    end
  end
end

app/helpers/shared/form_helper.rb
module Shared
  module FormHelper
    include FormConfig

    def render_form_field(f, key, options = {})
      default_options = { placeholder: key.titleize, class: "margin-reset" }

      field_type = SPECIFIC_FIELD_TYPES[key] || :text

      case field_type
      when :area
        f.text_area(key, default_options.merge(rows: options[:area_rows] || 4))
      when :date
        f.date_field(key, default_options)
      when :number
        f.number_field(key, default_options)
      when :dynamic_dropdown
        object_name = key.titleize.downcase

        link = link_to "Add New", send("new_#{object_name}_path"), data: { turbo_frame: "add_new_modal" }

        dd_options = f.object.class
          .send("load_#{object_name.pluralize}")
          .unshift(["Select a #{object_name}...", ""])

        select = f.select(key, dd_options)

        link + select
      when :regular_dropdown
        f.select(key, enum_keys(f.object.class, key))
      else
        f.text_field(key, default_options)
      end
    end

    def error_message_for(model, attribute)
      if model.errors[attribute].present?
        content_tag :small,
                    model.errors.full_messages_for(attribute).join(", "),
                    id: "#{attribute}_error",
                    class: "error-color"
      end
    end

    def enum_keys(klass, enum_name)
      klass.defined_enums[enum_name].keys
    end
  end
end

app/helpers/shared/index_helper.rb
module Shared
  module IndexHelper
    def object_attributes(object, id_column_shown = false)
      attributes = object.attributes.to_h
      attributes.delete("id") unless id_column_shown
      attributes
    end

    def previous_next_links(klass)
      params[:page] ||= 1
      current_page = params[:page].to_i
      total_records = klass.where(user_id: Current.user.id).count
      total_pages = (total_records.to_f / OBJECTS_PER_PAGE).ceil

      show_next_link = current_page < total_pages
      show_previous_link = current_page > 1

      previous_link = link_to "< Previous", action: "index", page: (current_page - 1) if show_previous_link
      next_link = link_to "Next >", action: "index", page: (current_page + 1) if show_next_link
      space_between = " | " if show_previous_link && show_next_link

      space_between ||= ""

      content = previous_link.to_s + space_between + next_link.to_s
      content_tag(:footer, content.html_safe) if show_previous_link || show_next_link
    end
  end
end

app/helpers/shared/show_helper.rb
module Shared
  module ShowHelper
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <span data-controller="flash" class="flash-background-<%= key %> flash-msg">
    <%= value %>
  </span>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <ul>
    <li><strong><%= link_to APP_NAME, root_path %></strong></li>
  </ul>
  <ul>
    <li>
      <%= link_to "Customers", customers_path %>
    </li>
    <li>
      <%= link_to "Cars", cars_path %>
    </li>
    <li>
      <details role="list">
        <summary  role="button"><%= Current.user.username %></summary>
        <ul role="listbox" class="margin-left-auto">
          <li>
            <%= link_to "Edit Password", password_path %>
          </li>
          <li>
            <%= link_to "Log out",  session_path(Current.user.id), data: {
                 turbo_method: :delete ,
                 turbo_confirm: "Are you sure?"
                 }
                 %>
          </li>
        </ul>
      </details>
    </li>
  </ul>
</nav>

app/views/shared/_search.html.erb
<%= form_with action: :index, method: :get, class: "margin-reset" do |f| %>
  <div class="index-search">
    <span class="flex-center margin-default-right">
      <%= link_to "Reset", {action: :index}, class: "margin-reset margin-default-right" if params[:query].present?%>
      <%= f.search_field :query, class: "margin-reset", value: params[:query] %>
    </span>
    <%= f.submit "Search" , class: "margin-reset" %>
  </div>
<% end %>

app/views/shared/_table-dd.html.erb
<details role="list" class="margin-reset">
  <summary>
    <%= image_tag "pen-icon.svg" %>
  </summary>
  <ul>
    <li>
      <%= link_to "View", action: "show", id: id %>
    </li>
    <li>
      <%= link_to "Edit", action: "edit", id: id %>
    </li>
    <li>
      <%= link_to "Delete", action: "delete", id: id %>
    </li>
  </ul>
</details>

app/views/shared/_table_dd.html.erb
<details role="list" class="margin-reset">
  <summary>
    <%= image_tag "pen-icon.svg" %>
  </summary>
  <ul>
    <li>
      <%= link_to "View", action: "show", id: id %>
    </li>
    <li>
      <%= link_to "Edit", action: "edit", id: id %>
    </li>
    <li>
      <%= link_to "Delete", action: "delete", id: id %>
    </li>
  </ul>
</details>